# Generated by Django 6.0.6 on 2026-06-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocklocation_alter_inventory_options_and_more'),
        ('purchases', '0002_alter_purchase_quantity_alter_purchase_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.stocklocation'),
        ),
    ]
