# Generated by Django 6.0.6 on 2026-06-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_location'),
        ('purchases', '0003_purchase_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.stocklocation'),
        ),
    ]
