# Generated by Django 6.0.6 on 2026-08-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchase_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='location',
        ),
    ]
