# Generated by Django 6.0.6 on 2026-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_sales_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SYSTEM_OWNER', 'SYSTEM_OWNER'), ('admin', 'Admin'), ('manager', 'Manager'), ('storekeeper', 'Storekeeper')], default='storekeeper', max_length=20),
        ),
    ]
