# Generated by Django 6.0.6 on 2026-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SYSTEM_OWNER', 'System Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('storekeeper', 'Storekeeper'), ('sales', 'Sales')], default='storekeeper', max_length=20),
        ),
    ]
