# Generated by Django 6.0.6 on 2026-08-25 18:33

import django.db.models.deletion
from django.db import migrations, models


def consolidate_inventory(apps, schema_editor):
    Inventory = apps.get_model('inventory', 'Inventory')
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        invs = list(Inventory.objects.filter(product=product).order_by('id'))
        if len(invs) > 1:
            total_qty = sum(inv.quantity for inv in invs)
            primary = invs[0]
            primary.quantity = total_qty
            primary.save()
            for extra in invs[1:]:
                extra.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_location'),
        ('products', '0002_alter_product_purchase_price_and_more'),
        ('purchases', '0005_remove_purchase_location'),
        ('sales', '0008_remove_saleitem_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventory'},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RunPython(consolidate_inventory, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.DeleteModel(
            name='StockLocation',
        ),
    ]
