# Generated by Django 6.0.6 on 2026-08-31 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options_and_more'),
        ('products', '0004_productgroup_product_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ADD', 'Stock In (Addition)'), ('REMOVE', 'Stock Out (Reduction)'), ('CORRECTION', 'Inventory Count Correction'), ('SALE', 'POS Sale Deduction'), ('PURCHASE', 'Supplier Purchase Inflow')], default='ADD', max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions/purchases, negative or delta for removals')),
                ('previous_quantity', models.PositiveIntegerField(default=0)),
                ('new_quantity', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(default='Manual adjustment', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
