# Generated by Django 6.0.6 on 2026-09-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'stock movement', 'verbose_name_plural': 'stock movements'},
        ),
    ]
