# Generated by Django 6.0.6 on 2026-06-08 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_sales_to_items(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    SaleItem = apps.get_model('sales', 'SaleItem')
    for sale in Sale.objects.all():
        SaleItem.objects.create(
            sale=sale,
            product=sale.product,
            quantity=sale.quantity,
            unit_price=sale.unit_price
        )


def reverse_copy(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    SaleItem = apps.get_model('sales', 'SaleItem')
    for item in SaleItem.objects.all():
        sale = item.sale
        sale.product = item.product
        sale.quantity = item.quantity
        sale.unit_price = item.unit_price
        sale.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_purchase_price_and_more'),
        ('sales', '0002_alter_sale_quantity_alter_sale_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.RunPython(copy_sales_to_items, reverse_code=reverse_copy),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
    ]
