# Generated by Django 6.0.6 on 2026-06-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocklocation_alter_inventory_options_and_more'),
        ('sales', '0003_remove_sale_product_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.stocklocation'),
        ),
    ]
