# Generated by Django 6.0.6 on 2026-06-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_location'),
        ('sales', '0004_saleitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.stocklocation'),
        ),
    ]
