# Generated by Django 6.0.6 on 2026-06-10 13:37

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateTimeField(default=sales.models.bd_now),
        ),
    ]
