# Generated by Django 6.0.6 on 2026-06-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_sold_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sold_at']},
        ),
    ]
