# Generated by Django 6.0.6 on 2026-08-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='location',
        ),
    ]
