# Generated by Django 6.0.6 on 2026-08-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productgroup_product_group'),
        ('sales', '0008_remove_saleitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='products.product'),
        ),
    ]
