# Generated by Django 6.0.6 on 2026-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_customer_address_sale_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10),
        ),
    ]
