# Generated by Django 6.0.6 on 2026-08-30 16:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_sale_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial / Due'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10),
        ),
    ]
