# Generated by Django 6.0.6 on 2026-08-30 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productgroup_product_group'),
        ('sales', '0012_sale_paid_amount_alter_sale_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Custom, unknown, or unlisted product name', max_length=255),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product'),
        ),
    ]
